# AUTOGENERATED! DO NOT EDIT! File to edit: ../../Notebooks/03_Utils/03_01_wandb_weights_logging.ipynb.

# %% auto 0
__all__ = ['flatten_params']

# %% ../../Notebooks/03_Utils/03_01_wandb_weights_logging.ipynb 3
import flax

# %% ../../Notebooks/03_Utils/03_01_wandb_weights_logging.ipynb 29
def flatten_params(params): return {"/".join(k): v for k, v in flax.traverse_util.flatten_dict(params).items()}
