# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/JaxPlayground',
                'doc_host': 'https://Jorgvt.github.io',
                'git_url': 'https://github.com/Jorgvt/JaxPlayground',
                'lib_path': 'JaxPlayground'},
  'syms': {}}
